### PR TITLE
Fix timezone issue (#15)

### PR DESCRIPTION
**Pull request by edno**
Fix issue #15 (invalid default timezone)

### CODE REVIEW

**Comment by codemedic** [comment]
Looks like you have not followed the [guide on contributions](/redmatter/Codeception-MultiDb/blob/master/README.md#how-to-contribute).
The change is based on master branch rather than on one of 1.0 or 2.0.
For now I will accept this change (will apply it myself to 1.0 and 2.0 branches), but will have to reject your PR though.

**Comment by edno** [comment]
My bad, I was not sure to which branch the fix applies to. Thanks for accepting it 😃

**Comment by codemedic** [comment]
@edno I hope you are aware that you can set the timezone from config.

See example below.

```
modules:
        Codeception\Extension\MultiDb:
            timezone: "+00:00"
            connectors:
                Primary:
                    dsn: "mysql:host=primary.db.example.com;port=3306;dbname=DemoConfig"
                    user: 'demo'
                    password: 'notsecure'
                    dump: 'tests/_data/primary.sql'
                    populate: true
                    cleanup: true
                Secondary:
                    dsn: "mysql:host=secondary.db.example.com;port=3306;dbname=DemoWarehouse"
                    user: 'demo'
                    password: 'notsecure'
                    dump: 'tests/_data/secondary.sql'
                    populate: true
                    cleanup: true
```

IMO, that is sufficient; we could do without this PR.

**Comment by edno** [comment]
Yep. My current configuration use the parameter `timezone` as a workaround. But from compatibility point of view, I think that would be better to use standard value for the default timezone.

**Pull request closed without merging**
